services:
  docmost:
    image: ghcr.io/lihaozhe013/docmost:hash
    environment:
      APP_URL: 'url'
      APP_SECRET: 'APP_SECRET'
      DATABASE_URL: 'postgresql://docmost:STRONG_DB_PASSWORD@host.docker.internal:5432/docmost'
      REDIS_URL: 'redis://host.docker.internal:6379'
    ports:
      - "127.0.0.1:3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    volumes:
      - docmost:/app/data/storage

volumes:
  docmost:
